"""Changed fields of PAYMENT

Revision ID: 02638685e33d
Revises: a0596ecc5a7f
Create Date: 2025-07-26 20:12:29.763883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02638685e33d'
down_revision: Union[str, None] = 'a0596ecc5a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('reason', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('payments', sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('payments', sa.Column('cancelled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'cancelled_at')
    op.drop_column('payments', 'performed_at')
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'reason')
    op.drop_column('payments', 'state')
    # ### end Alembic commands ###
