"""Validity period field changed

Revision ID: 0b88991a0fc6
Revises: de2d658141ac
Create Date: 2025-07-27 17:43:58.323641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b88991a0fc6'
down_revision: Union[str, None] = 'de2d658141ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promocodes', 'validity_period',
               existing_type=mysql.INTEGER(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promocodes', 'validity_period',
               existing_type=sa.Date(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
