"""Content duration added

Revision ID: 0c1fa44705e3
Revises: 6208aa927663
Create Date: 2025-07-11 12:52:22.239261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1fa44705e3'
down_revision: Union[str, None] = '6208aa927663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('content_duration', sa.String(length=255), nullable=True))
    op.add_column('contents', sa.Column('trailer_duration', sa.String(length=255), nullable=True))
    op.add_column('contents', sa.Column('type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'type')
    op.drop_column('contents', 'trailer_duration')
    op.drop_column('contents', 'content_duration')
    # ### end Alembic commands ###
