"""Added new model - UserHistory

Revision ID: 1849897d044f
Revises: f0f285063f8c
Create Date: 2025-07-10 00:22:44.283517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1849897d044f'
down_revision: Union[str, None] = 'f0f285063f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('contents_ibfk_2'), 'contents', type_='foreignkey')
    op.create_foreign_key(None, 'contents', 'users', ['uploader_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_tokens_ibfk_1'), 'user_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('user_tokens_ibfk_1'), 'user_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.create_foreign_key(op.f('contents_ibfk_2'), 'contents', 'users', ['uploader_id'], ['id'])
    op.drop_table('user_history')
    # ### end Alembic commands ###
