"""New column added - month to Promocode

Revision ID: 29e050449e98
Revises: 394c6d3b137c
Create Date: 2025-08-17 13:28:08.168742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e050449e98'
down_revision: Union[str, None] = '394c6d3b137c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocodes', sa.Column('month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promocodes', 'month')
    # ### end Alembic commands ###
