"""Added new field subscription date

Revision ID: 30f06ca8dfdc
Revises: dddf22cbc706
Create Date: 2025-07-27 20:34:38.099946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f06ca8dfdc'
down_revision: Union[str, None] = 'dddf22cbc706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subscription_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'subscription_date')
    # ### end Alembic commands ###
