"""Changed fields of PAYMENT

Revision ID: 334f7fdf0fb7
Revises: 02638685e33d
Create Date: 2025-07-26 20:13:32.710448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334f7fdf0fb7'
down_revision: Union[str, None] = '02638685e33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('extra_data', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'extra_data')
    # ### end Alembic commands ###
