"""Changed some fields

Revision ID: 3541e7c9cfe9
Revises: a58a28ae08ac
Create Date: 2025-07-29 19:32:34.541217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3541e7c9cfe9'
down_revision: Union[str, None] = 'a58a28ae08ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('payments', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payments', 'performed_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payments', 'cancelled_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'cancelled_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payments', 'performed_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payments', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payments', 'created_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
