"""Plan model changed

Revision ID: 394c6d3b137c
Revises: 15cfe6e99447
Create Date: 2025-08-06 14:46:39.870522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '394c6d3b137c'
down_revision: Union[str, None] = '15cfe6e99447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('month', sa.Integer(), nullable=True))
    op.drop_column('plans', 'title')
    op.drop_column('plans', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('plans', sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('plans', 'month')
    # ### end Alembic commands ###
