"""Changed some fields

Revision ID: 3a0f19770f6d
Revises: e64ca8903714
Create Date: 2025-07-29 19:47:47.390705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a0f19770f6d'
down_revision: Union[str, None] = 'e64ca8903714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at_ms', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('updated_at_ms', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('performed_at_ms', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('cancelled_at_ms', sa.BigInteger(), nullable=True))
    op.alter_column('payments', 'performed_at',
               existing_type=mysql.BIGINT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payments', 'cancelled_at',
               existing_type=mysql.BIGINT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'cancelled_at',
               existing_type=sa.DateTime(),
               type_=mysql.BIGINT(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payments', 'performed_at',
               existing_type=sa.DateTime(),
               type_=mysql.BIGINT(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('payments', 'cancelled_at_ms')
    op.drop_column('payments', 'performed_at_ms')
    op.drop_column('payments', 'updated_at_ms')
    op.drop_column('payments', 'created_at_ms')
    # ### end Alembic commands ###
