"""Added new field is_processing to Content and Episode models

Revision ID: 3fe0a8f70441
Revises: db186f86c905
Create Date: 2025-06-21 23:28:51.584419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe0a8f70441'
down_revision: Union[str, None] = 'db186f86c905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('is_processing', sa.Boolean(), nullable=True))
    op.add_column('episodes', sa.Column('is_processing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'is_processing')
    op.drop_column('contents', 'is_processing')
    # ### end Alembic commands ###
