"""Added ondelete to models

Revision ID: 452059d7ef8e
Revises: 2129692b6d62
Create Date: 2025-07-15 10:18:08.521283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452059d7ef8e'
down_revision: Union[str, None] = '2129692b6d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_history_ibfk_3'), 'user_history', type_='foreignkey')
    op.drop_constraint(op.f('user_history_ibfk_2'), 'user_history', type_='foreignkey')
    op.drop_constraint(op.f('user_history_ibfk_1'), 'user_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_history', 'contents', ['content_id'], ['content_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_history', 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_saved_ibfk_2'), 'user_saved', type_='foreignkey')
    op.drop_constraint(op.f('user_saved_ibfk_1'), 'user_saved', type_='foreignkey')
    op.drop_constraint(op.f('user_saved_ibfk_3'), 'user_saved', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved', 'contents', ['content_id'], ['content_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_saved', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_saved', 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_saved', type_='foreignkey')
    op.drop_constraint(None, 'user_saved', type_='foreignkey')
    op.drop_constraint(None, 'user_saved', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_ibfk_3'), 'user_saved', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_saved_ibfk_1'), 'user_saved', 'contents', ['content_id'], ['content_id'])
    op.create_foreign_key(op.f('user_saved_ibfk_2'), 'user_saved', 'episodes', ['episode_id'], ['id'])
    op.drop_constraint(None, 'user_history', type_='foreignkey')
    op.drop_constraint(None, 'user_history', type_='foreignkey')
    op.drop_constraint(None, 'user_history', type_='foreignkey')
    op.create_foreign_key(op.f('user_history_ibfk_1'), 'user_history', 'contents', ['content_id'], ['content_id'])
    op.create_foreign_key(op.f('user_history_ibfk_2'), 'user_history', 'episodes', ['episode_id'], ['id'])
    op.create_foreign_key(op.f('user_history_ibfk_3'), 'user_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
