"""Removed genre_id field

Revision ID: 47306b74134f
Revises: 2235099524ed
Create Date: 2025-06-10 21:40:18.248150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47306b74134f'
down_revision: Union[str, None] = '2235099524ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_genre',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ),
    sa.PrimaryKeyConstraint('content_id', 'genre_id')
    )
    op.drop_constraint(op.f('contents_ibfk_1'), 'contents', type_='foreignkey')
    op.drop_column('contents', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('genre', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('contents_ibfk_1'), 'contents', 'genres', ['genre'], ['genre_id'])
    op.drop_table('movie_genre')
    # ### end Alembic commands ###
