"""Changed fields of PAYMENT

Revision ID: 5d6520f9cd82
Revises: 89ee8db3a55d
Create Date: 2025-07-26 20:07:36.109340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d6520f9cd82'
down_revision: Union[str, None] = '89ee8db3a55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('gateway', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('account_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.String(length=255), nullable=True))
    op.drop_column('payments', 'gateway_1')
    op.drop_column('payments', 'transaction_id_1')
    op.drop_column('payments', 'account_id_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('account_id_1', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('payments', sa.Column('transaction_id_1', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('payments', sa.Column('gateway_1', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'account_id')
    op.drop_column('payments', 'gateway')
    # ### end Alembic commands ###
