"""Changed Content (added duration fields) and Episode

Revision ID: 6208aa927663
Revises: 1849897d044f
Create Date: 2025-07-10 15:45:18.363591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6208aa927663'
down_revision: Union[str, None] = '1849897d044f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episodes', 'seasion',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('episodes', 'episode',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('episodes', 'duration',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episodes', 'duration',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('episodes', 'episode',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('episodes', 'seasion',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
