"""Added on delete to models

Revision ID: 7706ee2cd8db
Revises: 837d7236a881
Create Date: 2025-08-21 06:14:00.224431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7706ee2cd8db'
down_revision: Union[str, None] = '837d7236a881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('episodes_ibfk_1'), 'episodes', type_='foreignkey')
    op.create_foreign_key(None, 'episodes', 'contents', ['content_id'], ['content_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('movie_genre_ibfk_1'), 'movie_genre', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genre', 'contents', ['content_id'], ['content_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_genre', type_='foreignkey')
    op.create_foreign_key(op.f('movie_genre_ibfk_1'), 'movie_genre', 'contents', ['content_id'], ['content_id'])
    op.drop_constraint(None, 'episodes', type_='foreignkey')
    op.create_foreign_key(op.f('episodes_ibfk_1'), 'episodes', 'contents', ['content_id'], ['content_id'])
    # ### end Alembic commands ###
