"""New fields added

Revision ID: 83edf5c8e255
Revises: 115132866f1f
Create Date: 2025-07-20 15:05:13.135276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83edf5c8e255'
down_revision: Union[str, None] = '115132866f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('original_content', sa.String(length=255), nullable=True))
    op.add_column('contents', sa.Column('converted_content', sa.String(length=255), nullable=True))
    op.add_column('contents', sa.Column('original_trailer', sa.String(length=255), nullable=True))
    op.add_column('contents', sa.Column('converted_trailer', sa.String(length=255), nullable=True))
    op.drop_column('contents', 'trailer_url')
    op.drop_column('contents', 'content_url')
    op.add_column('episodes', sa.Column('original_episode', sa.String(length=255), nullable=True))
    op.add_column('episodes', sa.Column('converted_episode', sa.String(length=255), nullable=True))
    op.drop_column('episodes', 'episode_video')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('episode_video', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('episodes', 'converted_episode')
    op.drop_column('episodes', 'original_episode')
    op.add_column('contents', sa.Column('content_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('contents', sa.Column('trailer_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('contents', 'converted_trailer')
    op.drop_column('contents', 'original_trailer')
    op.drop_column('contents', 'converted_content')
    op.drop_column('contents', 'original_content')
    # ### end Alembic commands ###
