"""Created new model - Payment

Revision ID: 89ee8db3a55d
Revises: a523fb3b6a2e
Create Date: 2025-07-26 20:05:53.554927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ee8db3a55d'
down_revision: Union[str, None] = 'a523fb3b6a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gateway_1', sa.String(length=100), nullable=True),
    sa.Column('account_id_1', sa.String(length=255), nullable=True),
    sa.Column('transaction_id_1', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
