"""Changed fields of PAYMENT

Revision ID: a0596ecc5a7f
Revises: 5d6520f9cd82
Create Date: 2025-07-26 20:08:36.187617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0596ecc5a7f'
down_revision: Union[str, None] = '5d6520f9cd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###
