"""Changed total_price field in Order

Revision ID: a523fb3b6a2e
Revises: 5e9afb7ca357
Create Date: 2025-07-26 19:59:21.986702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a523fb3b6a2e'
down_revision: Union[str, None] = '5e9afb7ca357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('amount', sa.BigInteger(), nullable=True))
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'amount')
    # ### end Alembic commands ###
