"""New model create - UserSaved

Revision ID: a8276a7edbb7
Revises: fbdfd2f2c031
Create Date: 2025-07-15 06:28:31.595628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8276a7edbb7'
down_revision: Union[str, None] = 'fbdfd2f2c031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_saved', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_saved', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_saved', type_='foreignkey')
    op.drop_column('user_saved', 'user_id')
    # ### end Alembic commands ###
