"""Created Episode model

Revision ID: ab6fc0b011ba
Revises: 
Create Date: 2025-06-21 22:14:38.718345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6fc0b011ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('content_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=10), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('dubbed_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('subscription_status', sa.Boolean(), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('content_url', sa.String(length=255), nullable=True),
    sa.Column('trailer_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['genre'], ['genres.genre_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('seasion', sa.String(length=25), nullable=True),
    sa.Column('episode', sa.String(length=50), nullable=True),
    sa.Column('episode_video', sa.String(length=255), nullable=True),
    sa.Column('episode_thumbnail', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('contents')
    op.drop_table('users')
    op.drop_table('genres')
    # ### end Alembic commands ###
