"""Changes in content model

Revision ID: db186f86c905
Revises: ab6fc0b011ba
Create Date: 2025-06-21 22:46:53.377580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db186f86c905'
down_revision: Union[str, None] = 'ab6fc0b011ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contents', 'users', ['uploader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'uploader_id')
    # ### end Alembic commands ###
