"""Added new field - Next payment date to Order

Revision ID: dddf22cbc706
Revises: 0b88991a0fc6
Create Date: 2025-07-27 18:31:56.081787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddf22cbc706'
down_revision: Union[str, None] = '0b88991a0fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('next_payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'next_payment_date')
    # ### end Alembic commands ###
