"""Added CASCADE

Revision ID: e38a82032622
Revises: 29e050449e98
Create Date: 2025-08-18 20:34:19.331008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38a82032622'
down_revision: Union[str, None] = '29e050449e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_ibfk_1'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'promocodes', ['promocode_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'promocodes', ['promocode_id'], ['id'])
    # ### end Alembic commands ###
