"""Changed some fields

Revision ID: e64ca8903714
Revises: 3541e7c9cfe9
Create Date: 2025-07-29 19:38:48.545700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e64ca8903714'
down_revision: Union[str, None] = '3541e7c9cfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'created_at',
               existing_type=mysql.BIGINT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('payments', 'updated_at',
               existing_type=mysql.BIGINT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.BIGINT(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
