"""UserToken

Revision ID: f0f285063f8c
Revises: 3b9958edf9db
Create Date: 2025-07-05 16:39:51.120617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0f285063f8c'
down_revision: Union[str, None] = '3b9958edf9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('user_device', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.drop_constraint(op.f('contents_ibfk_1'), 'contents', type_='foreignkey')
    op.drop_column('contents', 'genre')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('contents', sa.Column('genre', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('contents_ibfk_1'), 'contents', 'genres', ['genre'], ['genre_id'])
    op.drop_table('user_tokens')
    # ### end Alembic commands ###
