"""Added new field - duration to UserHistory

Revision ID: fb5ec5717500
Revises: 0c1fa44705e3
Create Date: 2025-07-14 21:10:28.170905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5ec5717500'
down_revision: Union[str, None] = '0c1fa44705e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('duration', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'duration')
    # ### end Alembic commands ###
